name: Feature Request
description: Request a new feature or enhancement
labels: ["enhancement", "feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for a new feature? We'd love to hear it!

  - type: dropdown
    id: type
    attributes:
      label: Feature type
      options:
        - New API endpoint
        - New data source
        - Analytics/statistics feature
        - Performance improvement
        - Data transformation
        - Integration (oneNinety dashboard)
        - Developer tooling
        - Other
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: Feature name
      description: A short name for this feature
      placeholder: "e.g., Player career stats endpoint"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem/Use case
      description: What problem does this solve? What's the use case?
      placeholder: |
        As a [type of user], I want to [do something]
        so that [benefit/outcome].
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How should this feature work?
      placeholder: |
        Describe the feature:
        - What data would it provide?
        - What parameters would it accept?
        - What format would the output be?
    validations:
      required: true

  - type: textarea
    id: existing
    attributes:
      label: Existing implementation
      description: Is this feature already in one of the existing repos?
      placeholder: |
        Check if this exists in:
        - nhl_apishift_v2
        - nhl_apimdc
        - NHLapiV3
        - etc.
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to help implement this feature
          required: false
