"""Pydantic schemas for viewer API responses."""

from nhl_api.viewer.schemas.coverage import (
    CategoryCoverage,
    CoverageResponse,
    SeasonCoverage,
)
from nhl_api.viewer.schemas.downloads import (
    ActiveDownload,
    ActiveDownloadsResponse,
    BatchCreated,
    CancelDownloadResponse,
    DownloadOptionsResponse,
    DownloadStartRequest,
    DownloadStartResponse,
    SeasonOption,
    SourceGroup,
    SourceOption,
)
from nhl_api.viewer.schemas.entities import (
    DivisionTeams,
    GameDetail,
    GameListResponse,
    GameSummary,
    PaginationMeta,
    PlayerDetail,
    PlayerListResponse,
    PlayerSummary,
    TeamDetail,
    TeamListResponse,
    TeamSummary,
    TeamWithRoster,
)
from nhl_api.viewer.schemas.reconciliation import (
    BatchReconciliationRequest,
    BatchReconciliationResponse,
    GameReconciliation,
    GameReconciliationDetail,
    ReconciliationCheck,
    ReconciliationDashboardResponse,
    ReconciliationGamesResponse,
    ReconciliationSummary,
)
from nhl_api.viewer.schemas.validation import (
    DiscrepanciesResponse,
    DiscrepancyDetail,
    DiscrepancySummary,
    QualityScore,
    QualityScoresResponse,
    ValidationResult,
    ValidationRule,
    ValidationRulesResponse,
    ValidationRunDetail,
    ValidationRunsResponse,
    ValidationRunSummary,
)

__all__ = [
    # Coverage
    "CategoryCoverage",
    "CoverageResponse",
    "SeasonCoverage",
    # Downloads
    "ActiveDownload",
    "ActiveDownloadsResponse",
    "BatchCreated",
    "CancelDownloadResponse",
    "DownloadOptionsResponse",
    "DownloadStartRequest",
    "DownloadStartResponse",
    "SeasonOption",
    "SourceGroup",
    "SourceOption",
    # Entities
    "DivisionTeams",
    "GameDetail",
    "GameListResponse",
    "GameSummary",
    "PaginationMeta",
    "PlayerDetail",
    "PlayerListResponse",
    "PlayerSummary",
    "TeamDetail",
    "TeamListResponse",
    "TeamSummary",
    "TeamWithRoster",
    # Reconciliation
    "BatchReconciliationRequest",
    "BatchReconciliationResponse",
    "GameReconciliation",
    "GameReconciliationDetail",
    "ReconciliationCheck",
    "ReconciliationDashboardResponse",
    "ReconciliationGamesResponse",
    "ReconciliationSummary",
    # Validation
    "DiscrepanciesResponse",
    "DiscrepancyDetail",
    "DiscrepancySummary",
    "QualityScore",
    "QualityScoresResponse",
    "ValidationResult",
    "ValidationRule",
    "ValidationRulesResponse",
    "ValidationRunDetail",
    "ValidationRunsResponse",
    "ValidationRunSummary",
]
